version: '3.8'
services:
  frontend:
    image: ${PROJECT_NAME}:dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
