FROM node:16-alpine AS builder
RUN apk add g++ make py3-pip

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

ARG ADMIN_URL_PROD
ENV ADMIN_URL_PROD=${ADMIN_URL_PROD}

RUN npm run build --prod

FROM nginx:alpine

COPY /nginx.conf  /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/fevg-client /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
